apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cors-proxy.fullname" . }}
  labels:
    {{- include "cors-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cors-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cors-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "cors-proxy.fullname" . }}-config