apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-flask-elastic-apm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "helm-flask-elastic-apm.name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "helm-flask-elastic-apm.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helm-flask-elastic-apm.name" . }}
    spec:
      containers:
      - name: flask-apm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.network.port }}
        env:
        - name: ELASTIC_APM_SERVICE_NAME
          value: "{{ .Values.apm.serviceName }}"
        - name: ELASTIC_APM_SERVER_URL
          value: "{{ .Values.apm.serverUrl }}"