apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
spec:
  selector:
    app: base-docker-registry
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}